# Generated by Django 5.0.7 on 2026-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cakes', 'Cakes'), ('cupcakes', 'Cupcakes'), ('cookies', 'Cookies'), ('breads', 'Breads'), ('chocolates', 'Chocolates'), ('custom', 'Custom')], max_length=20),
        ),
    ]
