# Generated by Django 6.0.4 on 2026-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cakes', 'Cakes'), ('cookies', 'Cookies'), ('cupcakes', 'Cupcakes'), ('chocolate', 'Chocolate'), ('bread', 'Bread'), ('special', 'Special Products')], max_length=50)),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], max_length=10)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
